<a href="https://colab.research.google.com/github/Haleel94/pytorch-deep-learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
tensor  = torch.rand(size =(7, 7))
tensor


tensor([[0.6653, 0.1655, 0.0335, 0.6029, 0.3845, 0.9800, 0.5517],
        [0.8354, 0.0061, 0.8769, 0.2743, 0.0955, 0.1052, 0.0416],
        [0.1276, 0.2834, 0.3169, 0.7796, 0.0479, 0.1126, 0.1521],
        [0.2441, 0.8072, 0.6690, 0.0250, 0.3466, 0.3309, 0.6736],
        [0.6927, 0.4636, 0.7779, 0.2272, 0.9819, 0.2837, 0.8507],
        [0.9106, 0.2870, 0.2761, 0.8426, 0.1181, 0.5230, 0.2799],
        [0.9037, 0.4367, 0.3503, 0.4920, 0.9301, 0.7231, 0.6418]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_2 = torch.rand(size = (1, 7))
# Perform matrix multiplication
#tensor_total = tensor * tensor_2
tensor_total = torch.matmul(tensor, tensor_2.T)
print(tensor_total)
tensor_total.shape

tensor([[1.4870],
        [1.4663],
        [1.2988],
        [1.6327],
        [2.3046],
        [1.9211],
        [2.3150]])


torch.Size([7, 1])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)
# Create two random tensors
tensor_1 = torch.rand(size = (3, 4))
tensor_2 = torch.rand(size = (4, 3))
# Matrix multiply tensors
Q = torch.matmul(tensor_1, tensor_2)
Q


tensor([[0.5445, 0.6972, 0.9362],
        [1.2350, 0.9886, 1.7153],
        [0.7619, 0.7761, 1.2287]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [9]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
cuda = torch.device('cuda')
print(cuda)
# Create two random tensors on GPU
T1 = torch.rand([2, 3]).cuda()
T2 = torch.rand([2, 3]).cuda()
print(T1)
print(T2)

cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
T_total =torch.mm(T1, T2.T)
T_total

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
z = torch.arange(0, 7)
print(z)
print(z.max())
# Find min
print(z.min())

tensor([0, 1, 2, 3, 4, 5, 6])
tensor(6)
tensor(0)


### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
print(z.argmax())

# Find arg min
print(z.argmin())

tensor(6)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x1 = torch.rand(size = (1, 1, 1, 10))
print(x1, x1.shape)

# Remove single dimensions
x2 = torch.rand(10)
print(x2, x2.shape)

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204, 0.0731, 0.9699,
        0.1078]) torch.Size([10])
